### ISSUE TITLE
File capability not applied

### ISSUE THREAD

**Issue by deric** [smoeding/puppet-file_capability#1]
Hi, I'm having problem with `file_capability` that aren't applying automatically:
```
Oct 14 09:24:37 w24 puppet-agent[16900]: (/File[/opt/puppetlabs/puppet/cache/lib/puppet/provider/file_capability]/ensure) created
Oct 14 09:24:38 w24 puppet-agent[16900]: (/File[/opt/puppetlabs/puppet/cache/lib/puppet/provider/file_capability/linux.rb]/ensure) defined content as 
Oct 14 09:24:47 w24 puppet-agent[16900]: (/File[/opt/puppetlabs/puppet/cache/lib/puppet/type/file_capability.rb]/ensure) defined content as '{md5}3cfc
Oct 14 09:25:27 w24 puppet-agent[16900]: (/Stage[main]/File_capability/File_capability[/usr/bin/telegraf]/ensure) created
Oct 14 09:27:03 w24 puppet-agent[16900]: Applied catalog in 109.45 seconds
```
the catalog was later successfully applied (but capability is not effectively set)
```
...
Oct 15 07:27:27 w24 puppet-agent[5769]: Applied catalog in 145.00 seconds
Oct 15 07:57:23 w24 puppet-agent[16848]: Applied catalog in 146.73 seconds
Oct 15 08:27:24 w24 puppet-agent[2603]: Applied catalog in 115.49 seconds
...
```
however the change is actually applied with corrective change when `puppet agent -t` is executed under root from shell:
```
$ puppet agent -t
...
Notice: /Stage[main]/File_capability/File_capability[/usr/bin/telegraf]/ensure: created (corrective)
Notice: Applied catalog in 17.64 seconds
root@w24.de ~ # getcap /usr/bin/telegraf
/usr/bin/telegraf = cap_net_admin,cap_net_raw+ep
```
From debug log:
```
Debug: file_capability: exists? /usr/bin/telegraf
Debug: Executing: '/sbin/setcap -q -v cap_net_admin,cap_net_raw=ep /usr/bin/telegraf'
Debug: Executing: '/sbin/getcap -v /usr/bin/telegraf'
Debug: file_capability: create /usr/bin/telegraf
Debug: Executing: '/sbin/setcap -q cap_net_admin,cap_net_raw=ep /usr/bin/telegraf'
Notice: /Stage[main]/File_capability/File_capability[/usr/bin/telegraf]/ensure: created (corrective)
Debug: /Stage[main]/File_capability/File_capability[/usr/bin/telegraf]: The container Class[File_capability] will propagate my refresh event
Debug: Class[File_capability]: The container Stage[main] will propagate my refresh event
```
Puppet agent is running as `root`, permissions shouldn't be problem:
```
root     21909  0.0  0.0 230948 18740 ?        Sl   Oct13   1:04 /opt/puppetlabs/puppet/bin/ruby /opt/puppetlabs/puppet/bin/mcollectived --config=/etc/puppetlabs/mcollective/server.cfg --pidfile=/var/run/puppetlabs/mcollective.pid --daemonize
```
```
# puppet --version
5.5.16
```
OS is Debian 9: `4.9.110-3+deb9u6`.

Any ideas what could be wrong?

**Comment by smoeding** [comment]
Looking at the log entry from `Oct 14 09:25:27` in your first log I would say that the capabilities have been set correctly. So Puppet not doing anything the next runs would be the expected thing.

Currently I don't understand why `puppet agent -t` would want to change anything then.

Have you tried to purge the capabilities from the file (using `/sbin/setcap -r /usr/bin/telegraf`) and then wait until Puppet runs? Does it change anything? What does `getcap` show after this when you do not run Puppet manually?

The process you showed is not Puppet but `mcollective`. Can you verify again that Puppet runs as `root`?

**Comment by deric** [comment]
Right, sorry. Both processes `mcollective` and `puppet` run under `root`. The problem was that meanwhile puppet upgraded telegraf package. Thus the `/usr/bin/telegraf` binary has changed and capabilities were gone. 

The capabilities were set or unset depending on the order of upgrading and setting capabilities. In order to effectively apply capabilities the service must be restarted, thus a notify is needed:
```puppet
File_capability['/usr/bin/telegraf'] ~> Service['telegraf']
```
Any idea if I'm able to configure this via hiera? Something like:
```puppet
file_capability::file_capabilities:
  '/usr/bin/telegraf':
    ensure:     present
    capability: 'cap_net_admin,cap_net_raw=ep'
    notify:     Service['telegraf]
```

**Comment by smoeding** [comment]
The `file_capablities` parameter values are given _as-is_ to the type. So I would expect it to accept common meta parameters like `notify`. However , I haven't tested this.
